site_name: Kinkkukiusaus
site_url: https://kinkku.kiusa.us/
repo_name: aa8855/kinkkukiusaus
repo_url: https://github.com/aa8855/kinkkukiusaus/
theme: 
  name: simple-blog
  components:
    footer: false
    title: false
    site_name: false
  theme_style: dark
  
nav:
  - Kinkkukiusaus: 'index.md'
